### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by mark-in**

### CODE REVIEW

**Comment by DonnchaC** [comment]
Hi Ivan, sorry for the delay in getting back to you. It doesn't look like the 'service-perm-signature' field will be implemented in Tor. If you create a pull request without the commits ec472d9 and e74fdcf I can merge these changes. Just so you know I'll probably be starting this project fresh in a few weeks.

**Comment by mark-in** [comment]
Hello Donncha! 
Oops, sorry. Please check out the new PR.
Do you mean that you are planning to rewrite this project from scratch as TSoP project?

**Comment by DonnchaC** [comment]
I'm not sure yet, I might change the design or architecture a little in the TSoP project, so it might be best to start fresh. Thank you for the interest and the pull requests!

**Comment by mark-in** [comment]
Thank you for your awesome idea and its implementation! I wish you good luck with your TSoP project! It promises to be interesting!

**Pull request closed without merging**
